name: Application Release

on:
  push:
    tags:
      - "v1.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            ## Changelog
          draft: false
          prerelease: false
  movetag:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - uses: actions/checkout@v2
      - name: Update major version tag
        id: update_major_version_tag
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          MAJOR=${VERSION%%.*}

          git config user.name github-actions
          git config user.email github-actions@github.com

          git tag --annotate ${MAJOR} --message 'Update major version tag' --force
          git push origin ${MAJOR} --force